### PR TITLE
S4 is done. Implemented HIP-29, & 179. Also addressed bug HIP-208.

### PR DESCRIPTION
**Pull request by NAMSTERR**
In this PR I implemented HIP-29, & 179. Also addressed bug HIP-208.

**_Few thing's to note_**

1.) For the Customer Messages page:

- The way the functionality work is quite simple. Before testing the functionality make sure to register a new customer on the app, set their shipping info. Second buy/checkout a product. Third send a message on the contact page. Fourth logout. Fifth log in as admin: (username = **hcsadmin**, password =  **NiceDragon123!**), and go to the Customer Messages page.
- Now you should be able to see a view of the Customer Messages page where you should be seeing the new user/their info, along with the product type they purchased, and their city. 

2.) For the Customer Chat page:

- While still being logged in as user 'hcsadmin', go to the Customer Chat page. Here you should be able to archive/unarchive user's as you please. One big thing to note. All messages sent from registered users account, are sent to the new admin account I made 'hcsadmin'. I am hoping these admin creds can be passed on to the client to use.  

3.) Why I made admin 'hcsadmin'?

- So this was in response to bug HIP-208. The web app doesn't currently have the capability to allow users/admins to change their usernames. And so with that in mind I figured it would be best to make seed credentials for the Client, and route all messages that come in from the sites communication interface to be directed to 'hcsadmin'. 

fig1
[Figure 1]

### CODE REVIEW

**Review by Dfreem — CHANGES_REQUESTED** [review]
# Code Review  PR 95

**Author**- Nehemiah John
**Reviewer** - Devin Freeman

## Found Issues

I found the following issues during a review of this pull request.
### <small>Admin Users cannot see or respond to messages sent by a newly registered user</small>:

**steps to recreate**:

- register a new user to the site.
- navigate to the contacts page and send a message.
- Log out of new user and log in as an admin user.

Figure 1. shows the users that are in the admin role currently
<small>(**including the new admin user that was added in this PR**)</small>



**Issue in the scenario:**

- All of these users should be able to read a message sent to admin.
- The PR notes for this pull indicate that you must have shipping info saved and are also required to have purchased an item first in order to send a message to the owner/s of the sites. Although in need of some updating, the design documents don't mention this stipulation, and I was unable to find any conversation that the team had discussed it.

---

### <small>While signed in as a user in the Admin role, searching for messages returns no results.</small>

**steps to recreate:**

1. While signed in as a non-admin user, navigate to contact and send a message.
2. Sign out and sign back in as any user in the admin role.
3. Navigate to Customer Messages.
4. Search for the user that you sent the message as in step 2.
  a. ***Example***: I registered user `TestUser` with the following properties:
    First Name = "first"
    Last Name = "last"
    User Name = "TestUser"

**Issues in the Scenario**:

- When I followed this procedure, the search results for the first, last and username all returned no results. Additionally searching for the date, product and City also return no results.

---

### <small>While signed in as an admin user, after sending messages as a non-admin user, the admin is unable to see the conversation in the Customer Chat</small>

**steps to recreate:**

1. after sending a message while signed in as an admin user, sign out and back in as an admin user.
2. navigate to the Customer Chat view.
3. click on the UserName of the user that you sent the message as.

**Issues in the Scenario:**

1. the customer messages are not accessible by the admin users, if their username is not `hcsadmin`.

---

### <small>While signed in as an admin user (`hcsadmin` included), only one archived conversation will display the messages contained in it.</small>

**steps to recreate:**

1. Start > 2 conversations with a user
2. sign in as an admin user, and archive all the conversations.
3. navigate to the archived chats, and select each conversation.

**Issues in the Scenario:**
- only one of the archived conversation is able to be accessed while there are more than one archived conversation..
- if the intent is for archived conversations contents to not be visible, then the opposite issue is true, there is still one conversation that is able to be read.
---

**Comment by NAMSTERR** [comment]
**Thank you for the thorough review once again! I appreciate your feedback, and I'll address each of your concerns below.**
---

### _**Issue 1: Admin Users cannot see or respond to messages sent by a newly registered user:**_

In regard to this issue, I want to clarify a few points. Firstly, we never explicitly discussed whether all admins should receive user messages. On 5/2/23 (See figure 1), I mentioned that I would assign all messages sent from registered accounts to Michael's account on the app, but it seems this was overlooked. Additionally, my initial PR provided detailed instructions for testing the implemented features, and I believe you may have missed a step, which led to the behavior you described.

To recreate the issue you mentioned, I followed these steps:
1. Registered a new user named 'Hun'.
2. Proceeded to the contact page and sent a message without performing any other actions.
3. Logged out of the 'Hun' account and logged in as admin 'nehemiah123!' (See figure 2).

As you can see in figure 2, the message is visible to admin 'nehemiah.' I also logged in as Devin, and the message was visible to him as well (See figure 3). Therefore, all admins should be able to see messages in the Customer Messages section. But only 'hcsadmin' will be able to see, receive, and send messages to registered users (this is an intentional behavior).

Regarding the requirement for shipping info and purchasing an item, my PR notes were specific to the user story I implemented (HIP-29). Nowhere did I state that shipping info is necessary to send a message. In my PR, I asked to add shipping info after creating the account to showcase the feature fully. As shown in figure 5, the recently created user 'Hun' doesn't have any product info or city specified because I didn't set any shipping info or make a purchase. However, in figures 6 to 10, I demonstrated the sequence of adding shipping info, making a purchase, and sending a message to the admin.

---
### _**Issue 2: While signed in as a user in the Admin role, searching for messages returns no results:**_

Regarding the filtering tool behavior, I believe if you follow the steps and clarifications provided above, you will not encounter the issue you described. It's possible that after you re-ran the migrations for my PR and performed a DB update, the DB didn't have adequate data, resulting in no search results.

Here's an explanation of what each field in the filtering tool expects as input:
- Sender: Enter a name from the sender column.
- Date Sent: Enter a date from the date sent column.
- Product: Enter a product type from the product column.
- City: Enter a city name from the city column.

To illustrate the filtering tool based on the scenarios you mentioned:
1. Figure 11 displays all the messages currently in the DB.
2. Figure 12 shows the search results when I entered 'Bob' in the Sender field, retrieving all the messages exchanged between admins and Bob.
3. Figure 13 demonstrates the search for user 'Bob' on 5/31/23, resulting in a single row, as it's the only message associated with Bob on that date.
4. Figure 14 displays the expected output when the following values are entered in the fields:

-    Sender: Bob
-    Date Sent: 05/29/2023
-    Product: Butterfly Test
-    City: Eugene
-It returns two rows, as expected.

5. Figure 15 demonstrates the filtering by 'Butterfly Test' in the product field, resulting in five rows.
---

### _**Issue 3: While signed in as an admin user, after sending messages as a non-admin user, the admin is unable to see the conversation in the Customer Chat:**_ 

The steps you provided for reproducing this issue didn't yield the behavior you described on my machine. In fact, I observed the expected behavior, where the admin can see the messages sent by non-admin users.

Before delving deeper into this concern, it's important to note the following about the Customer Chat page:
- All administrators have the ability to archive or unarchive registered users.
- All administrators can send messages to non/registered users.
- However, only the 'hcsadmin' user possesses the capability to both receive new messages from and send messages to registered users.

Before we explore this concern further, it is essential to understand the following details regarding the Customer Chat page:

- Figures 16 to 20 demonstrate the ability to send and receive messages from registered users. In figure 16, I sent a message to registered user 'Elevation' from admin Michael's account, and figure 17 shows that the user indeed received the message. Figure 18 illustrates a message sent by user 'Bob,' which was received by 'hcsadmin' (figure 19), while other admins, including Devin, didn't receive the message (Figure 20) which is expected behavior.

---

### _**Issue 4: While signed in as an admin user (hcsadmin included), only one archived conversation will display the messages contained in it.**_

- I am not to sure as to why you are only able to view only one archived users messages, on my machine I am not able to replicate the behavior you describe. In figure 21 you can observe two recently created users which I just archived. And in figure 22&23 you can see that I am able to view each of the users conversations. 


Based on these observations, I believe this PR fulfills the user stories, and I hope it can be merged into the main branch so that I may move onto addressing sprint 5 user stories. Please feel free to reach out if you have any further questions or concerns.

Thank you!
---

f23
[Figure 23]

f22
[Figure 22]

f21
[Figure 21]

f20
[Figure 20]

f19
[Figure 19]

f18
[Figure 18]

f17
[Figure 17]

f16
[Figure 16]

f15
[Figure 15]

f14
[Figure 14]

f13
[Figure 13]

f12
[Figure 12]

f11
[Figure 11]

f10
[Figure 10]

f9
[Figure 9]

f8
[Figure 8]

f7
[Figure 7]

f6
[Figure 6]

f5
[Figure 5]

f4
[Figure 4]

f3
[Figure 3]

f2
[Figure 2]

f1
[Figure 1]

**Comment by Dfreem** [comment]
The previous review was lacking in documenting images, I'd like to provide clarification in addition to the previously submitted response.

The instructions provided with the original request to merge were followed as well as the test scenarios included in the original response.

- An image of the instructions submitted with this pull request. Here we are instructed to create a new user, set their shipping info and buy a product. The instructed test was conducted along with others.



- A screen recording of the issue in question.

https://github.com/paulsenm/HipAndClavicle/assets/102371929/c71047bb-266b-4890-9d0c-c2479a5185fb

- The explanation for the functionality of the archived messages was slightly inaccurate, my appologies for the confusion. What is happening in reality is if one is logged in as the user with the username 'hcsadmin' then you are indeed able to see all the user messages both archived and un-archived
-  The issue is observed when logged in as an admin user without the username 'hcsadmin'. The feature allows an admin to send messages from the chat view. If several messages are started and archived with registered users, the archiving behavior is intermittent as described.
- The reason this is a problem, is because this would mean that the client would not have the ability to set the admin user without hiring a programmer/developer.

**Comment by ProfBird** [comment]
I can see that this PR has been problematic for both Nehemiah and the reviewers. Here is my advice for resolving the disagreements on this PR as well as others in the future. Hopefully what you learn from this will be helpful on your first Software Dev job in the near future.

As I mentioned in my previous e-mail, many misunderstandings and disagreements can be resolved through better documentation. In particular:
- The requirements that go with a user story should be detailed in the notes for that user story on Jira.
- The dev who implements a user story should write a functional test for that user story. BTW, a functional test is also a form of documentation that describes in a concrete way what the functionality is.

General comments on this PR and PRs in general:
Here are things that I believe could have or will make the code review, revisions, and acceptance go more smoothly:
1. A PR should be for just one user story, unless the implementation of one user story can’t be tested without implementing another.
   This PR is for multiple user stories. I don’t know if that was necessary, but it’s something to try to avoid.
2. The user stories lack descriptions. There are no details of the desired functionality.
3. User stories and the bug are marked done even though they are not. They should not be marked done until the PR i is accepted and the code merged into main.
4. The user stories and bug are either not in a sprint or in a sprint that is already closed. If a user story isn’t done by the end of a sprint,  and is still a priority it should be moved to the new sprint.
5. The bug, HIP-208, has no description of the desired behavior.

Regarding disagreements on the PR

1. Customer Messages (HIP-191? or is it HIP-29?)
- It’s not clear which user story this is for.
- No formal test case has been added to the functional test document.
- Devin’s code review seems reasonable given the user story. I don’t see any requirement anywhere in the project documentation that permission for this feature is only for a “super admin”, hcsadmin.

2. Customer Chat (HIP-179)
- No formal test case in the functional test doc.
- Again, the issue Devin found seems to be related to functionality only working for the “super admin”.

3. Why I made admin “hcsadmin”
- It’s good that Nehemiah explained this, but this new category of “super admin” was not part of the project requirements and should not have been added without that being requested by the client or having been a design change that was approved and documented by the team.
- It makes sense to me that there should just be one kind of admin, not a separate “super admin”.


Summary of User Stories and the bug on this PR

HIP-29: Seller can sort customer messages by date, customer location, product, etc
- This story has no description.
- It is in sprint 4, but that sprint is completed.
- It is marked done, even though the code has not been accepted for merge to main.

HIP-179: An admin will be able to archive a user and their messages on customer chat view.
- This story has no description.
- It is in sprint 4.
- It is marked as done, but not accepted for merge to main.

HIP-191: A admin will be able to send the users emails by clicking on the the clients email in AllCustomerMesseges view.
- Has no description.
- In sprint 4.
- Marked as done, but code not accepted for merged to main.

HIP-208: All messages made by a logged in user that are not an admin are currently all directed to the AppUser with the user name ‘michael123’
- Has a description with reasons for this being a bug, but no description of the desired behavior.
- Not assigned to a sprint.
- Marked as done, but code not accepted for merged to main.

All the best,
Brian

Brian Bird
Faculty
Computer Information Technology
Lane Community College
lanecc.edu/cit <https://www.lanecc.edu/cit>
linkedin.com/in/brianabird <http://linkedin.com/in/brianabird>

**Comment by NAMSTERR** [comment]
I have decided to close this pull request (#95) in favor of a new one that I will submit soon. The current pull request has become quite convoluted, and I believe many of the concerns raised were not explicitly discussed before. Therefore, I kindly request the team to address any concerns or questions they may have regarding the issues below which I will be addressing in my next pull request. It would be greatly appreciated if these concerns are brought up now rather than after the pull request goes live. 
---
**Issue 1:**
* The capability to see/receive/send messages should be extended to all administrators, not just limited to the 'hcsadmin' user.
* Note to self: Consider modifying the functionality so that when any user sends a message, it gets sent to a queue which all admins will have access to. Depending on the currently logged-in admin user, they can respond to or view any message as desired.

**Issue 2:**
* All users with the admin role should have access to messages received on the Customer Chat page, not just restricted to 'hcsadmin'.

**Issue 3:**
* Each conversation with a registered user on the customer messages page should be displayed in a single row.
* The client/admin should be able to click on a button to open the entire conversation with a particular customer and send or reply to them directly on the customer messages page.

**Pull request closed without merging**
