### PR TITLE
Mwp images Hip-172

### PR DESCRIPTION
**Pull request by paulsenm**
Got images to save and display on listings. Fixed bug with item colors in customer order history.

### CODE REVIEW

**Comment by NAMSTERR** [comment]
Reviewer: Nehemiah John

**Mwp images Hip-172 #93**

EDIT: This error below was addressed by Michael 5-27-23 6:55 PM.

Everything for the most part works as intended. Although I did notice one issue. 

- If you are logged in as the user 'michael123!', and hit the 'Your Orders' tab in nav, an error gets thrown (See figure 1). One thing to note, this error is not occurring when I did the same exact steps while logged in as myself. 

[Figure 1]
Screenshot 2023-05-27 at 6 31 06 PM

**Review by NAMSTERR — CHANGES_REQUESTED** [review]
Checkout my comment in the PR comment thread.

**Review by NAMSTERR — APPROVED** [review]
This is good to merge into main. Michael addressed the one error I found.

**Review by Dfreem — DISMISSED** [review]
You and I discussed an issue when trying to navigate to the Customer Orders page as some users. A screenshot of the error is included below.
image

using the particular LINQ experession `FirstOrDefault()` will create a new object of the specified type if it is not found. By changing this call to an index instead, we can see that in fact this collection is empty when the error occurs. This can be fixed by checking to see if the list is empty prior to accessing the items, for instance in an if statement. I believe this is the cause of the specific error. While it may indicate other, larger design errors, I believe that the addidition of an empty check to the Orders view would eliminate the error.

**Pull request merged**
