### PR TITLE
HIP-191 done. Also added a short paragraph to home page.

### PR DESCRIPTION
**Pull request by NAMSTERR**
-Implemented HIP-191
-Added a short paragrpah from clients ETSY site on home page.

**What does this implementation allow admin users to do?**
1.) Send/create an email template by clicking on the email of a user or email icon on the AllCustomerMesseges view.
2.) View messages regardless of the length of the message by clicking on the view message button.

Screenshot 2023-05-24 at 5 18 30 PM

### CODE REVIEW

**Comment by bradysteven06** [comment]
was it intended for the default email client to open when clicking send on the email? if it was, the output I got when testing it was messy and needed to be re-entered before it could be sent.
image

**Review by bradysteven06 — APPROVED** [review]

**Comment by NAMSTERR** [comment]
> was it intended for the default email client to open when clicking send on the email? if it was, the output I got when testing it was messy and needed to be re-entered before it could be sent.
> image

Addressed this with Steven on Discord. This is good to merge.

**Review by Dfreem — DISMISSED** [review]
# PR 91

**Submitting Contributor**: Nehemiah John

**Reviewer**: Devin Freeman

Commit Message:
> HIP-191 done. Also added a short paragraph to home page

---
The following issues should be revised before merging the PR.


**EDIT**: 5/25 - I was able to get the mailto to work.
- ~~Filling out the send email form and clicking the send button opens a blank browser page and no email is sent. <small>(**see figure 5**)</small>~~
- Paragraph on the Welcome page was not part of the original design and was not discussed by the team as part of Hip - 191. As discussed by the entire team at the stand-up on 5/25 a better location for this would be the about page, however it is not a high priority, therefore should be removed for the time being.
- All messages made by a logged in user that is not an admin are currently all directed to the AppUser with the user name 'michael123'. This is an issue for the following reasons:
  - If the user with this specific user name changes their user name, this causes an error as there are no results in the collection when attempting to retrieve that user.
  - The owner of the site will not have the user nam of 'michael123'. An admin has a Role of 'Admin'. Using this Role eliminates these issues.

- While logged in as an admin that is not using the user name 'michael123' I am able to see all the emails sent to another administrator. This functionality in isolation would not pose a problem, the issue is that an administrator, the messages sent to the administrator are accessible from the "Customer Messeges" <small>(**see figure 1**)</small> View but not accessible from the "CustomerChat" view <small>(**see figure 2**)</small>
- "Customer Messeges" should be "Customer Messages"<small>(**see figure 6**)</small>.
- "CustomerChat" should be two words, "Customer Chat"<small>(**see figure 6**)</small>.

figure 1.


figure 2.


figure 3.


figure 4.


figure 5.


figure 6.

**Comment by NAMSTERR** [comment]
Hey! Thanks for the thorough feedback @Dfreem! I am gonna respond to each of your points in the same sequence you made your points.

1.) The paragraph I added is removed now.

2.) All messages being directed to user 'michael123' is an intentional behavior, as I mentioned in our discussion on 5/2/23, but I believe it may have been overlooked. (See figure 1). 

   2A/2B.) These sound like a very valid concern/bug. Which should be addressed in a bug ticket on JIRA. Not on a PR          
   that has nothing to do with the implementation of the specific user story (HIP-191) I made.
   
3.) I think you may be miss understanding the functionality of the messaging system here. The "CustomerChat" view is only to show those users and their messages, who are registered on the site. On the other hand the "Customer Messeges" view is a over all the general place for the client to go to, and see messages from registered users & unregistered. The "Customer Messeges" page is sort of like a over all user friendly view of what's in the database in terms of messages. 

4 & 5.) Will make a syntactic bug ticket for these spelling errors, and address them.

Moving forward I am hoping this PR can be merged into main as it has an approval from a team member already. 

figure 1
[figure 1]

**Comment by NAMSTERR** [comment]
This PR covers HIP-185 & HIP-191. Along with some minor cosmetic changes, and a few bug fixes.

Also putting a screenshot of the NUnit tests running here for posterity:
Screenshot 2023-05-26 at 11 29 37 AM

**Review by paulsenm — APPROVED** [review]
Bug fix looks like it's working. Cosmetic fixes for next sprint/PR would be to get the Customer Message view down to one row per customer and have reply functionality built into View Message modal.

**Pull request merged**
