### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by bradysteven06**
-Added HIPNunitTests project to the solution

### CODE REVIEW

**Comment by Dfreem** [comment]
when I pull this, I see the test project, and there is nothing wrong with anything, but I also don't see any test's. It's looks like a new empty test project. Was there suppose to be more included on this this Pull? There are also no reviewers included here on github.

**Comment by bradysteven06** [comment]
I made the project so when Miah and I work on the tests there will not be any conflicts with both of us creating the Nunit test project

**Comment by Dfreem** [comment]
I asked Brian about this, it sounds like it should be fine, if you want to pull in main and update this as well as include reviewers someone can approve it.

**Comment by bradysteven06** [comment]
merged main and added two empty test classes for product and shoppingcart

**Review by NAMSTERR — APPROVED** [review]
This looks good Steven.

**Pull request merged**
